namespace Starnight.Internal.Entities.Guilds.Audit;

/// <summary>
/// Enumerates the different kinds of audit log entries.
/// </summary>
public enum DiscordAuditLogEvent
{
	GuildUpdated = 1,
	ChannelCreated = 10,
	ChannelUpdated = 11,
	ChannelDeleted = 12,
	ChannelOverwriteCreated = 13,
	ChannelOverwriteUpdated = 14,
	ChannelOvewriteDeleted = 15,
	MemberKicked = 20,
	MemberPruned = 21,
	MemberBanned = 22,
	MemberUnbanned = 23,
	MemberUpdated = 24,
	MemberRolesUpdated = 25,
	MemberMove = 26,
	MemberDisconnected = 27,
	BotAdded = 28,
	RoleCreated = 30,
	RoleUpdated = 31,
	RoleDeleted = 32,
	InviteCreated = 40,
	InviteUpdated = 41,
	InviteDeleted = 42,
	WebhookCreated = 50,
	WebhookUpdated = 51,
	WebhookDeleted = 52,
	EmojiCreated = 60,
	EmojiUpdated = 61,
	EmojiDeleted = 62,
	MessageDeleted = 72,
	MessagesBulkDeleted = 73,
	MessagePinned = 74,
	MessageUnpinned = 75,
	IntegrationCreated = 80,
	IntegrationUpdated = 81,
	IntegrationDeleted = 82,
	StageInstanceCreated = 83,
	StageInstanceUpdated = 84,
	StageInstanceDeleted = 85,
	StickerCreated = 90,
	StickerUpdated = 91,
	StickerDeleted = 92,
	GuildScheduledEventCreated = 100,
	GuildScheduledEventUpdated = 101,
	GuildScheduledEventDeleted = 102,
	ThreadCreated = 110,
	ThreadUpdated = 111,
	ThreadDeleted = 112,
	ApplicationCommandPermissionsUpdated = 121
}
